version: "2.1"
services:
  react-container:
    build:
      context: ./react-jwt-auth/react-jwt-auth/
      dockerfile: Dockerfile
    volumes:
      - ./react-jwt-auth/react-jwt-auth:/app/client #PERMET DE MODIFIER LES FICHIER SANS REBUILD DOCKER
    ports:
      - 8081:8081
    container_name: react-container
    command: npm start

  node-container:
    build:
      context: ./node-js-jwt-auth/
      dockerfile: Dockerfile
    volumes:
      - ./react-jwt-auth/react-jwt-auth/public/pdf:/app/server/pdf/
      - ./node-js-jwt-auth:/app/server #PERMET DE MODIFIER LES FICHIER SANS REBUILD DOCKER
    ports:
      - 8080:8080
    container_name: node-container
    command: npm start
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    container_name: db-react-container
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql #RENDRE LA DB PERSISTANTE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_HOST: node-container
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 5
